server:
  port: 8080


#查看springboot开启了哪些配置
debug: false

spring:
  profiles:
    active: dev

---
#开发环境配置
spring:
  profiles: dev

server:
  port: 8080

---
#测试环境配置
spring:
  profiles: test

server:
  port: 8081

---
#生产环境配置
spring:
  profiles: prod

server:
  port: 8082




#配置actuator可访问所有节点
management:
    endpoints:
        web:
            exposure:
                include: "*"

spring:
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/boot
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.winter.model



system:
  serverId: apple


